# Избранные предложения
## Получить список избранных объявлений

GET http://localhost:7777/favorites HTTP/1.1
Content-Type: application/json

###

## Добавить объявление из избранного

POST http://localhost:7777/favorites/63f629e8da9132b3def9e62d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzZjVlOTY5YzYxYzc0NGM0YzVlOGE5NSIsInVzZXJuYW1lIjoiTmV3X1VzZXIiLCJlbWFpbCI6Im5ld3VzZXJAZ21haWwuY29tIiwidXNlclN0YXR1cyI6IlBybyIsImlhdCI6MTY3NzA2MDQ2NCwiZXhwIjoxNjc3MjMzMjY0fQ.oRSSDCAJmU6uqfrDMU8__S66IHQeg9w7mz4d3NDMqt8

###

## Удалить объявление из избранного

DELETE http://localhost:7777/favorites/63f5f96f4adab447ca50e120 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzZjVlOTY5YzYxYzc0NGM0YzVlOGE5NSIsInVzZXJuYW1lIjoiTmV3X1VzZXIiLCJlbWFpbCI6Im5ld3VzZXJAZ21haWwuY29tIiwidXNlclN0YXR1cyI6IlBybyIsImlhdCI6MTY3NzA2MDQ2NCwiZXhwIjoxNjc3MjMzMjY0fQ.oRSSDCAJmU6uqfrDMU8__S66IHQeg9w7mz4d3NDMqt8

###
