# Избранные предложения
## Получить список избранных объявлений

GET http://localhost:7777/favorites HTTP/1.1
Content-Type: application/json

###

## Добавить/удалить объявление из избранного

PATCH http://localhost:7777/favorites/63dd55c86535a4d5b29c06fd/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzZWU5MzFhY2E3Yjc2OWY5MjI3MDkwMiIsImVtYWlsIjoibmV3dXNlckBnbWFpbC5jb20iLCJpYXQiOjE2NzY2NDA3ODIsImV4cCI6MTY3NjgxMzU4Mn0.0zMckAfaDRwcuxImjevYIiynX4OvpL4WjVMRLvAR4Vc

###
