openapi: 3.0.1
info:
  title: API сервер для проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 3.0.0
tags:
  - name: rent-offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.
  - name: favorites
    description: Действия с избранными объявлениями.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

  /users/logout:
    delete:
      tags:
        - users
      summary: Завершение работы пользователя
      description: Завершает сеанс работы — выход из авторизации.

  /favorites:
    get:
      tags:
        - favorites
      summary: Получение списка избранных предложений
      description: Возвращает все предложения, добавленные в избранное.

  /favorites/{rentId}/{status}:
    post:
      tags:
        - favorites
      summary: Изменение статуса избранного объявления
      description: Добавление или удаление предложения в/из избранного. Возвращает предложение с идентификатором rentId с актуальным состоянием поля isFavorite
